// ─────────────────────────────────────────────────────────────────────────────
// FEATURE SLICE 1: Counter (Synchronous actions)
//
// INTERVIEW CONCEPT:
//   createSlice() bundles:
//     - name        → namespace for action types  (e.g. "counter/increment")
//     - initialState → the slice's initial data
//     - reducers    → synchronous action handlers (Immer-powered, mutate freely)
//     - selectors   → co-located state selectors
//
//  Immer allows "mutating" syntax inside reducers; it produces immutable updates.
// ─────────────────────────────────────────────────────────────────────────────

import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import type { RootState } from '../../store'

interface CounterState {
  value: number
  step: number
  history: number[]
}

const initialState: CounterState = {
  value: 0,
  step: 1,
  history: [],
}

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    // Action: counter/increment
    increment(state) {
      state.history.push(state.value)
      state.value += state.step
    },
    // Action: counter/decrement
    decrement(state) {
      state.history.push(state.value)
      state.value -= state.step
    },
    // Action: counter/incrementByAmount — PayloadAction types the payload
    incrementByAmount(state, action: PayloadAction<number>) {
      state.history.push(state.value)
      state.value += action.payload
    },
    // Action: counter/reset
    reset(state) {
      state.history.push(state.value)
      state.value = 0
    },
    // Action: counter/setStep
    setStep(state, action: PayloadAction<number>) {
      state.step = action.payload
    },
  },
})

// ── Action Creators (auto-generated by createSlice) ──────────────────────────
export const { increment, decrement, incrementByAmount, reset, setStep } =
  counterSlice.actions

// ── Selectors ─────────────────────────────────────────────────────────────────
export const selectCount = (state: RootState) => state.counter.value
export const selectStep = (state: RootState) => state.counter.step
export const selectHistory = (state: RootState) => state.counter.history

export default counterSlice.reducer
